package cfg

type builtInFilterList struct {
	Name           string
	Type           FilterListType
	URL            string
	HomepageURL    string
	Trusted        bool
	DefaultEnabled bool
	Locales        []string
}

var builtInFilterLists = []builtInFilterList{
	{
		Name:           "Zen - Ads",
		Type:           "ads",
		URL:            "https://raw.githubusercontent.com/ZenPrivacy/filter-lists/master/ads/ads.txt",
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "EasyList",
		Type:           "ads",
		URL:            "https://easylist.to/easylist/easylist.txt",
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "AdGuard Base filter",
		Type:           "ads",
		URL:            "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt",
		Trusted:        true,
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "EasyPrivacy",
		Type:           "privacy",
		URL:            "https://easylist.to/easylist/easyprivacy.txt",
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "AdGuard Spyware filter",
		Type:           "privacy",
		URL:            "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt",
		Trusted:        true,
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "DandelionSprout's URL Shortener",
		Type:           "privacy",
		URL:            "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt",
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "Online Malicious URL Blocklist",
		Type:           "malware",
		URL:            "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-online.txt",
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "Phishing URL Blocklist",
		Type:           "malware",
		URL:            "https://malware-filter.gitlab.io/malware-filter/phishing-filter.txt",
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "Dan Pollock's hosts file",
		Type:           "general",
		URL:            "https://someonewhocares.org/hosts/zero/hosts",
		HomepageURL:    "",
		DefaultEnabled: true,
	},
	{
		Name:           "Peter Lowe's Ad and tracking server list",
		Type:           "general",
		URL:            "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext",
		HomepageURL:    "",
		DefaultEnabled: false,
	},
	{
		Name:           "🇦🇱AL 🇽🇰XK Adblock List for Albania and Kosovo",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/AnXh3L0/blocklist/master/albanian-easylist-addition/Albania.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"al", "xk"},
	},
	{
		Name:           "🇪🇬EG 🇸🇦SA 🇲🇦MA 🇩🇿DZ: Liste AR",
		Type:           "regional",
		URL:            "https://easylist-downloads.adblockplus.org/Liste_AR.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"eg", "sa", "ma", "dz"},
	},
	{
		Name:           "🇧🇬BG: Bulgarian Adblock List",
		Type:           "regional",
		URL:            "https://stanev.org/abp/adblock_bg.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"bg"},
	},
	{
		Name:           "🇨🇳CN 🇹🇼TW: AdGuard Chinese Filter (中文)",
		Type:           "regional",
		URL:            "https://filters.adtidy.org/extension/ublock/filters/224.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"cn", "tw"},
	},
	{
		Name:           "🇨🇿CZ 🇸🇰SK: Easylist Czech and Slovak Filter List",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/tomasko126/easylistczechandslovak/master/filters.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"cz", "sk"},
	},
	{
		Name:           "🇩🇪DE 🇨🇭CH 🇦🇹AT: EasyList Germany",
		Type:           "regional",
		URL:            "https://easylist.to/easylistgermany/easylistgermany.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"de", "ch", "at"},
	},
	{
		Name:           "🇪🇪EE: Eesti saitidele kohandatud filter",
		Type:           "regional",
		URL:            "https://adblock.ee/list.php",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"ee"},
	},
	{
		Name:           "🇫🇮FI: Adblock List for Finland",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/finnish-easylist-addition/finnish-easylist-addition/gh-pages/Finland_adb.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"fi"},
	},
	{
		Name:           "🇫🇷FR 🇨🇦CA: AdGuard French filter",
		Type:           "regional",
		URL:            "https://filters.adtidy.org/extension/ublock/filters/16.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"fr", "ca"},
	},
	{
		Name:           "🇬🇷GR 🇨🇾CY: Greek AdBlock Filter",
		Type:           "regional",
		URL:            "https://www.void.gr/kargig/void-gr-filters.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"gr", "cy"},
	},
	{
		Name:           "🇭🇷HR 🇷🇸RS: Dandelion Sprout's Serbo-Croatian filters",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/SerboCroatianList.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"hr", "rs"},
	},
	{
		Name:           "🇭🇺HU: hufilter",
		Type:           "regional",
		URL:            "https://filters.hufilter.hu/hufilter-adguard.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"hu"},
	},
	{
		Name:           "🇮🇩ID 🇲🇾MY: ABPindo",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/ABPindo/indonesianadblockrules/master/subscriptions/abpindo.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"id", "my"},
	},
	{
		Name:           "🇮🇳IN 🇱🇰LK 🇳🇵NP: IndianList",
		Type:           "regional",
		URL:            "https://easylist-downloads.adblockplus.org/indianlist.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"in", "lk", "np"},
	},
	{
		Name:           "🇮🇷IR: PersianBlocker",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/MasterKia/PersianBlocker/main/PersianBlocker.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"ir"},
	},
	{
		Name:           "🇮🇸IS: Icelandic ABP List",
		Type:           "regional",
		URL:            "https://adblock.gardar.net/is.abp.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"is"},
	},
	{
		Name:           "🇮🇱IL: EasyList Hebrew",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/easylist/EasyListHebrew/master/EasyListHebrew.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"il"},
	},
	{
		Name:           "🇮🇹IT: EasyList Italy",
		Type:           "regional",
		URL:            "https://easylist-downloads.adblockplus.org/easylistitaly.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"it"},
	},
	{
		Name:           "🇯🇵JP: AdGuard Japanese Filter",
		Type:           "regional",
		URL:            "https://filters.adtidy.org/extension/ublock/filters/7.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"jp"},
	},
	{
		Name:           "🇰🇷KR: Fanboy's Korean",
		Type:           "regional",
		URL:            "https://www.fanboy.co.nz/fanboy-korean.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"kr"},
	},
	{
		Name:           "🇱🇹LT: EasyList Lithuania",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/EasyList-Lithuania/easylist_lithuania/master/easylistlithuania.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"lt"},
	},
	{
		Name:           "🇱🇻LV: Latvian List",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/Latvian-List/adblock-latvian/master/lists/latvian-list.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"lv"},
	},
	{
		Name:           "🇲🇰MK: Macedonian adBlock Filters",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/DeepSpaceHarbor/Macedonian-adBlock-Filters/master/Filters",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"mk"},
	},
	{
		Name:           "🇳🇱NL 🇧🇪BE: EasyList Dutch",
		Type:           "regional",
		URL:            "http://easylist-downloads.adblockplus.org/easylistdutch.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"nl", "be"},
	},
	{
		Name:           "🇳🇴NO 🇩🇰DK 🇮🇸IS: Dandelion Sprouts nordiske filtre for ryddigere nettsider",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/NorwegianList.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"no", "dk", "is"},
	},
	{
		Name:           "🇵🇱PL: Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"pl"},
	},
	{
		Name:           "🇵🇱PL: Oficjalne polskie filtry przeciwko alertom o Adblocku",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/olegwukr/polish-privacy-filters/master/anti-adblock.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"pl"},
	},
	{
		Name:           "🇷🇴RO 🇲🇩MD: Romanian Ad (ROad) Block List Light",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/tcptomato/ROad-Block/master/road-block-filters-light.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"ro", "md"},
	},
	{
		Name:           "🇷🇺RU 🇺🇦UA 🇺🇿UZ 🇰🇿KZ: RU AdList",
		Type:           "regional",
		URL:            "https://easylist-downloads.adblockplus.org/ruadlist.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"ru", "ua", "uz", "kz"},
	},
	{
		Name:           "🇪🇸ES 🇦🇷AR 🇲🇽MX 🇨🇴CO: EasyList Spanish",
		Type:           "regional",
		URL:            "https://easylist-downloads.adblockplus.org/easylistspanish.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"es", "ar", "mx", "co"},
	},
	{
		Name:           "🇪🇸ES 🇦🇷AR 🇧🇷BR 🇵🇹PT: AdGuard Spanish/Portuguese",
		Type:           "regional",
		URL:            "https://filters.adtidy.org/extension/ublock/filters/9.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"es", "ar", "br", "pt"},
	},
	{
		Name:           "🇸🇮SI: Slovenian List",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/betterwebleon/slovenian-list/master/filters.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"si"},
	},
	{
		Name:           "🇸🇪SE: Frellwit's Swedish Filter",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Filter.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"se"},
	},
	{
		Name:           "🇹🇭TH: EasyList Thailand",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/easylist-thailand/easylist-thailand/master/subscription/easylist-thailand.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"th"},
	},
	{
		Name:           "🇹🇷TR: AdGuard Turkish Filter",
		Type:           "regional",
		URL:            "https://filters.adtidy.org/extension/ublock/filters/13.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"tr"},
	},
	{
		Name:           "🇻🇳VN: ABPVN List",
		Type:           "regional",
		URL:            "https://raw.githubusercontent.com/abpvn/abpvn/master/filter/abpvn_ublock.txt",
		HomepageURL:    "",
		DefaultEnabled: false,
		Locales:        []string{"vn"},
	},
}

func isBuiltInURL(url string) bool {
	for _, b := range builtInFilterLists {
		if b.URL == url {
			return true
		}
	}
	return false
}
