# Refer to golangci-lint's example config file for more options and information:
# https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

linters:
  enable:
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - gocritic
    - stylecheck
    - unparam
    - asciicheck
    - prealloc
    - predeclared
    - makezero
    - bidichk
    - godot
    - tparallel
  disable:
    - errcheck
    - goimports # Gives false positives on Windows.

run:
  modules-download-mode: readonly
  timeout: 5m

linters-settings:
  gosec:
    config:
      # Maximum allowed permissions mode for os.OpenFile and os.Chmod
      # Default: "0600"
      G302: "0644"
      # Maximum allowed permissions mode for os.WriteFile and ioutil.WriteFile
      # Default: "0600" 
      G306: "0644"

issues:
  exclude-files:
    - internal/systray/systray_internal_windows.go
