version: "2"

run:
  modules-download-mode: readonly
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bidichk
    - gocritic
    - godot
    - gosec
    - importas
    - makezero
    - misspell
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
  disable:
    - errcheck
  settings:
    gosec:
      config:
        G302: "0644"
        G306: "0644"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          # These give false positives for Windows API-related identifier names.
          - revive
          - staticcheck
        path: (.+)_windows.go

formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
