version: '3'

includes:
  build: tasks/build/Taskfile-{{OS}}.yml
  scriptlets: scriptlets/Taskfile.yml
  frontend: frontend/Taskfile.yml

tasks:
  default:
    desc: Runs the dev task.
    cmds:
      - task: dev

  dev:
    desc: Runs the application in development mode.
    cmds:
      - wails dev

  build-dev:
    desc: Create a development build of the application.
    cmds:
      - wails build

  test-go:
    desc: Run Go tests.
    cmds:
      - go test -cover -race ./...

  test:
    desc: Run Go and scriptlets tests.
    cmds:
      - task: scriptlets:test
      - task: test-go
      - cmd: echo "Tests passed"
        silent: true

  lint:
    desc: Run frontend, scriptlets, and Go linters.
    cmds:
      - task: frontend:lint
      - task: scriptlets:lint
      - task: lint-go
      - cmd: echo "Checks passed"
        silent: true

  lint-go:
    desc: Run Go linters.
    cmds:
      - golangci-lint run
