// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cfg} from '../models';
import {sync} from '../models';

export function AddCustomFilterList(arg1:cfg.CustomFilterList):Promise<void>;

export function AddFilterLists(arg1:Array<cfg.FilterList>):Promise<void>;

export function GetCAInstalled():Promise<boolean>;

export function GetCustomFilterLists():Promise<Array<cfg.CustomFilterList>>;

export function GetFilterLists():Promise<Array<cfg.FilterList>>;

export function GetIgnoredHosts():Promise<Array<string>>;

export function GetLocale():Promise<string>;

export function GetMyRules():Promise<Array<string>>;

export function GetPACPort():Promise<number>;

export function GetPort():Promise<number>;

export function GetUpdatePolicy():Promise<cfg.UpdatePolicyType>;

export function GetVersion():Promise<string>;

export function Lock():Promise<void>;

export function RLock():Promise<void>;

export function RLocker():Promise<sync.Locker>;

export function RUnlock():Promise<void>;

export function RemoveCustomFilterList(arg1:string):Promise<void>;

export function RunMigrations():Promise<void>;

export function Save():Promise<void>;

export function SetCAInstalled(arg1:boolean):Promise<void>;

export function SetIgnoredHosts(arg1:Array<string>):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function SetMyRules(arg1:Array<string>):Promise<void>;

export function SetPort(arg1:number):Promise<string>;

export function SetUpdatePolicy(arg1:cfg.UpdatePolicyType):Promise<void>;

export function ToggleFilterList(arg1:string,arg2:boolean):Promise<void>;

export function TryLock():Promise<boolean>;

export function TryRLock():Promise<boolean>;

export function Unlock():Promise<void>;
