name: Feature Request
description: Suggest a new feature or improvement for Zen
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to suggest a feature in Zen.
        Before submitting the issue, please [refer to the project roadmap](https://github.com/anfragment/zen/discussions/99) and [search the issue tracker](https://github.com/anfragment/zen/issues) to see if it is already being worked on.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the feature you would like to see in Zen. Include a detailed description of why it is needed.
        Attach screenshots or videos if it helps explain the feature.
    validations:
      required: true
