version: '3'

tasks:
  build:
    desc: Builds the bundle and copies it to the internal/extendedcss directory.
    dir: extended-css
    cmds:
      - npm run build
      - cp dist/bundle.js ../internal/extendedcss
      - du -sh ../internal/extendedcss/bundle.js
      - echo -n "" >> ../main.go

  lint:
    desc: Lints the code.
    dir: extended-css
    cmds:
      - npm run lint

  test:
    desc: Tests the code.
    dir: extended-css
    cmds:
      - npm run test

  install:
    desc: Installs the complete set of dependencies.
    dir: extended-css
    cmds:
      - npm ci

  install-prod:
    desc: Installs the dependencies required to build the bundle.
    dir: extended-css
    cmds:
      - npm ci --only=prod
