name: Upload release manifest

on:
  release:
    types: [released]

jobs:
  upload-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version-file: scripts/package.json
          cache: 'npm'
          cache-dependency-path: scripts/package-lock.json
      - name: Run node --version
        run: node --version
      - name: Install dependencies
        run: npm ci --omit=dev
        working-directory: scripts
      - name: Run upload-manifest
        run: npm run upload-manifest
        working-directory: scripts
