name: Test

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  test-go:
    name: Test Go (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - name: Run go version
        run: go version
      - name: Set up Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create placeholder asset
        # go:embed requires the directory to exist and be non-empty
        run: |
          mkdir -p ./frontend/dist
          touch ./frontend/dist/placeholder
      - name: Run tests
        run: task test
